apiVersion: v1
kind: Service
metadata:
  name: yap-nodeport-service
  namespace: yap-eks-activity
spec:
  type: NodePort
  selector:
    app: httpd-app
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 5678
      nodePort: 30001